### ISSUE TITLE
null: false generates nullable association when used in belongs_to

### ISSUE THREAD

**Issue by ppraisethesun** [bamorim/typed_ecto_schema#30]
null: false only makes a foreign key field non-nullable
```
typed_schema "" do
  belongs_to :client, User, null: false
end

generates the following spec:

@type t :: %Order{
  client: Ecto.Schema.belongs_to(User.t()) | nil,
  client_id: integer()
}
```

I think it should make the association field non-nullable too

**Comment by dvic** [comment]
@bamorim I believe this was intentional?

In theory you could have a relation without a fk and then you could have the situation where there is a fk set but the fetched relation is null. I believe this is what Ecto will do in these situations, you can verify this.

**Comment by bamorim** [comment]
@dvic, technically if you are using a fk it shouldn't be null when fetched. But we don't have db schema information here. Not sure what would be the best approach here.

**Comment by dvic** [comment]
I think it makes sense to make it non-nil, even though technically it could be nil if the schema doesn't use proper foreign key constraints. In 99% of the cases this will be the correct thing to do I think.

**Comment by dvic** [comment]
(at least in our schema's we use foreign key constraints everywhere)

**Comment by bamorim** [comment]
Fair enough. I agree. I think we should change that behaviour. Should that also be the case for has_one?
That would be technically a breaking change, so we shall bump the version to 0.5.0.
