### ISSUE TITLE
Is there any support for many-to-many relation

### ISSUE THREAD

**Issue by pankaj-ag** [bamorim/typed_ecto_schema#5]
Thank you for this package. It works great. 

I just want to know that is there any way I can have many-to-many relations in the TypedEctoSchema module?

**Comment by bamorim** [comment]
@pankaj-ag I don't think I've done that but it is easy to add this. I'll tackle that this weekend.

Sorry for the delay in the response, it got lost in the GitHub notifications.

**Comment by ericlathrop** [comment]
It appears to output `term()` for the typespec on many_to_many associations, when it should be something like `[MyType.t()] | nil`. Overriding the type produces this error:

```
** (CompileError) lib/sql_membership_provider/role.ex:21: misplaced operator ::/2

The :: operator is typically used in bitstrings to specify types and sizes of segments:

    <<size::32-integer, letter::utf8, rest::binary>>

It is also used in typespecs, such as @type and @spec, to describe inputs and outputs
    expanding macro: Ecto.Schema.schema/2
```

**Comment by bamorim** [comment]
Hey @pankaj-ag and @ericlathrop. Sorry for being unresponsive. I'll take a deeper look into that as soon as I have time.

**Comment by ericlathrop** [comment]
No worries! I would've made a PR myself, but I got distracted by all my own projects that I'm neglecting :wink:

**Comment by bamorim** [comment]
@ericlathrop @pankaj-ag 

I have just opened a PR for this: https://github.com/bamorim/typed_ecto_schema/pull/9

I haven't tested much though, but it looks like it is working.

If you have spare time and would like to help me testing and reviewing code, that would be appreciated.

I'll however wait for #8 to be merged first and will rebase it later.
